---
apiVersion: batch/v1
kind: Job
metadata:
  name: go-demo-app-migration
  labels:
    app: go-demo-app-job
spec:
  template:
    spec:
      containers:
        - name: migration-job
          image: go-demo-app:latest
          command:
            - /bin/sh
            - -c
            - echo "Running migration"
      restartPolicy: Never
