---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-volume
  labels:
    app: go-demo-app-volume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app-volume
  template:
    metadata:
      labels:
        app: go-demo-app-volume
    spec:
      containers:
        - name: go-demo-app
          image: go-demo-app:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-config
              mountPath: /etc/config
              readOnly: true
            - name: app-logs
              mountPath: /var/log/app
            - name: app-data
              mountPath: /app/data
      volumes:
        - name: app-config
          configMap:
            name: go-demo-app-config
        - name: app-logs
          emptyDir: {}
        - name: app-data
          persistentVolumeClaim:
            claimName: go-demo-app-pvc
