---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-demo-app-cronjob
  labels:
    app: go-demo-app-cronjob
spec:
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: go-demo-app-batch
              image: go-demo-app:latest
              command:
                - /bin/sh
                - -c
                - echo "Running batch job"
          restartPolicy: OnFailure
