---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-readiness
  labels:
    app: go-demo-app-readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo-app-readiness
  template:
    metadata:
      labels:
        app: go-demo-app-readiness
    spec:
      containers:
        - name: go-demo-app
          image: go-demo-app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
