apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  USERNAME: YWRtaW4=    # "admin" base64 encoded
  PASSWORD: c2VjcmV0    # "secret" base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-secret
  labels:
    app: nginx-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-secret
  template:
    metadata:
      labels:
        app: nginx-secret
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD
