---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-liveness
  labels:
    app: go-demo-app-liveness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo-app-liveness
  template:
    metadata:
      labels:
        app: go-demo-app-liveness
    spec:
      containers:
        - name: go-demo-app
          image: go-demo-app:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
