---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app-resources
  labels:
    app: go-demo-app-resources
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo-app-resources
  template:
    metadata:
      labels:
        app: go-demo-app-resources
    spec:
      containers:
        - name: go-demo-app
          image: go-demo-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
