---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
  labels:
    app: go-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
        - name: go-demo-app
          image: go-demo-app:latest
          ports:
            - containerPort: 8080
